### ISSUE TITLE
MIT license, add README file, github templates and badges

### ISSUE THREAD

**Issue by ktaranov** [SQLUndercover/UndercoverToolbox#1]
Hello, guys.

Do you want to add some description in README file and github badges and templates like in my repo ? I can help with it if you accepted MIT or another type of open source licence https://github.com/ktaranov/sqlserver-kit

**Comment by SQLUndercover** [comment]
Thanks for the offer of help, much appreciated :).  We have been looking at open source licenses to offer our scripts under and MIT is looking like a good option.  We do need to put a README together and probably organise things a bit better.
