### ISSUE TITLE
Inspector - Backup Space report including backups to other drives

### ISSUE THREAD

**Issue by PeterJenner1992** [SQLUndercover/UndercoverToolbox#168]
i'm looking at the backup space section. And we've had a warning come through for lack of space on the backup drive.
When i've looked into it, it looks as though it's been triggered by a backup which is backing up to a different location.
So you have backup location A, which the report is saying doesn't have space
And Backup location B where the Database is going (which has plenty of space for the backup)
it's like it's ignoring where the backup is actually taking to

**Comment by Adedba** [comment]
Thanks for reporting the issue @PeterJenner1992 

Unfortunately you have hit a design restriction , we wrongly assumed that all servers being reportied on by your Central server would all use the same backup path when indeed this is not actually going to be the case! but I think we can make that better for V2.

so the way it is now is....
Inspector.Settings has a setting called BackupPath ...or something similar and this has a single value which is used for all the servers which are in Inspector.CurrentServers WHERE Isactive = 1
Problem with that is that you may have servers and/or databases being reported on which are taking backups to a a different location and this is where it falls over.

Leave this one with me and I will find a way to make this work better and get the change into V2.

**Comment by Adedba** [comment]
The backupsPath setting in the Inspector. Settings table will support a comma delimited list of paths, each path will be checked individually and highlight individually.
