### ISSUE TITLE
Inspector - Inspector.DatabaseGrowthsInsert does not handle FILESTREAM files

### ISSUE THREAD

**Issue by AlexGay** [SQLUndercover/UndercoverToolbox#205]
**Describe the bug**
When run on a server with filestream files configured you get the error "Arithmetic overflow error for data type tinyint. value = 65537.

**To Reproduce**
Create a new database file of type FILESTREAM Data for any database on the server by following these steps.
1. Right click on the database.
2. Click on the files tab.
3. Click on the Add button.
4. Enter a value in the Logical name field, Change File Type to FILESTREAM Data.
5. Enter a value for Size (MB).
6. Click OK.
7. Run Inspector.InspectorDataCollection, or the appropriate job.

**Expected behavior**
Updated data to be added to Inspector.DatabaseFileSizes.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version [e.g. 22]: 79.0.3945.130

**Additional context**
This error is caused by the file_id value for FILESTREAM files which is 65537. This is set by Microsoft and so not changeable.

My local fix for this was:
ALTER TABLE [Inspector].[DatabaseFileSizes]
ALTER COLUMN [File_id] INT NOT NULL;
GO

**Comment by Adedba** [comment]
Hi @AlexGay , 

Thank you for the bug report and thank you for the fix! I will get this update added to the January updates due in the next couple of days.

**Comment by Adedba** [comment]
included the DatabaseFileSizeHistory table as this too has the File_id column.
