### ISSUE TITLE
Inspector - Email priority is always Low.

### ISSUE THREAD

**Issue by AlexGay** [SQLUndercover/UndercoverToolbox#213]
**Describe the bug**
The report email priority is always set to low even when there are urgent warnings in the report.

**To Reproduce**
1. Install Inspector V2 from the setup script.
2. Run a data collection job with a module that will generate a warning condition.
3. Run a data report job to an appropriate email address.
4. The email has the Low priority even though the report contains warnings.

**Expected behavior**
The email priority should change depending on the importance of the report contents.

**Screenshots**
![image](https://user-images.githubusercontent.com/8024781/77431681-f0e11a80-6dd4-11ea-9299-ae5bac5aaef2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 74.0

**Additional context**
In the Stored Procedure [Inspector].[SQLUnderCoverInspectorReport] there are several calls to [Inspector].[GenerateHeaderInfo] which passes in the argument @Importance.  In the Stored Procedure [Inspector].[GenerateHeaderInfo] the @Importance parameter is marked as OUTPUT, but the OUTPUT keyword is not included in the Stored Procedure calls in [Inspector].[SQLUnderCoverInspectorReport].  When the OUTPUT keyword is added in the three appropriate places the expected behavior occurs.

**Comment by Adedba** [comment]
Nice catch!! thanks for reporting it and thanks for the fix! will get this rolled out as a minor release this month.
