### ISSUE TITLE
sp_RestoreScript: full backup filename is followed by '0' (zero) character 

### ISSUE THREAD

**Issue by rubaboo** [SQLUndercover/UndercoverToolbox#295]
**Describe the bug**
Generated script has an extraneous `0` (zero) character after the full backup filename. No zero after a log backup filename.

**To Reproduce**
Run sp_RestoreScript. Observe the command `… FROM DISK = '…\filename.bak'0 WITH NORECOVERY…`

**Additional context**
Latest version sp_RestoreScript 1.8

**Comment by UndercoverDavid** [comment]
Thanks for raising this, I'll have a look into it.

**Comment by rubaboo** [comment]
Fixed in https://github.com/SQLUndercover/UndercoverToolbox/commit/d84f32a6984efe60cc0be77779c429743b64da0c. Thank you.
