### ISSUE TITLE
InspectorPS - Add email upon failure to Powershell collection

### ISSUE THREAD

**Issue by Adedba** [SQLUndercover/UndercoverToolbox#63]
Might be worth adding an email upon failure feature to the PS collection , this can default to sending the email from the Central server using the email address/s specified in the email config of the Inspector, but alternatively can have parameters to allow the user to email from Powershell instead by specifying SMTP server, credentials and recipient.

**Comment by shaneis** [comment]
Just adding this command here we talked about today so we have a history of it

`Send-MailMessage`
