### ISSUE TITLE
InspectorPS - Add $ModuleConfig as a Param for Powershell collection

### ISSUE THREAD

**Issue by Adedba** [SQLUndercover/UndercoverToolbox#64]
$ModuleConfig is used in the powershell collection to pass a value to @ModuleConfig when executing [Inspector].[InspectorDataCollection] e.g. 

EXEC [$LoggingDb].[Inspector].[InspectorDataCollection] @ModuleConfig = $ModuleConfig

The param should be a data type of string and behave as follows:

- No value passed -Set $ModuleConfig to NULL (as a string with no apostrophe encapsulation.

- If a value is passed - Set $ModuleConfig to the string value passed but encapsulate in apostrophes e.g Default would become 'Default'.

Validation on $ModuleConfig is already taken care of to ensure that the module config exists in the Inspector ModuleConfig table , when this is null the moduleconfig will be auto determined (within SQL) on a server by server basis.

**Comment by shaneis** [comment]
Sounds good, want to give it a go yourself? You have the blueprints there

**Comment by Adedba** [comment]
Yeah I will give this a go :)

**Comment by Adedba** [comment]
Included in Pull #84
